// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dahswdlernfjiijyavbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhaHN3ZGxlcm5mamlpanlhdmJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNDQzNzYsImV4cCI6MjA3NzkyMDM3Nn0.Lzy-WOgTfAPyGwWS7otCTv4oJ9XiIknxR9bwATexcoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});